name: Build Thesis

on:
  push:
  pull_request:
    paths:
      - '**.tex'
      - '**.bib'
      - '**.cls'
      - '**.sty'
      - '.github/workflows/latex.yml'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf
          path: thesis.pdf
